arch: FibNet
args: true
batch_size: 640
block_depth: 5
config: configs\config.yml
data: ISLRV
dist_backend: nccl
dist_url: tcp://224.66.41.62:23456
epochs: 200
evaluate: false
gpu: 0
lr: 0.05
momentum: 0.9
multiprocessing_distributed: false
n_blocks: 8
pretrained: false
print_freq: 10
rank: -1
resume: ''
seed: null
start_epoch: 0
use_conv_cat: true
weight_decay: 0.0001
workers: 2
world_size: -1
