arch: FibNet
args: true
batch_size: 250
block_depth: 5
n_blocks: 8
data: ./ILSVRC/Data/CLS-LOC/
dist_backend: nccl
dist_url: tcp://224.66.41.62:23456
epochs: 250
evaluate: false
gpu: 0
lr: 0.05
momentum: 0.9
multiprocessing_distributed: false
pretrained: false
print_freq: 10
rank: -1
resume: ''
seed: null
start_epoch: 0
use_conv_cat: true
weight_decay: 0.0001
workers: 2
world_size: -1
